#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`
cp -r dynamicCode.orig dynamicCode
runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication extrudeMesh
cp 0/T.orig 0/T
runApplication buoyantBoussinesqPimpleFoam
runApplication -s sample  postProcess -func sample

#------------------------------------------------------------------------------
